
FROM noed/se2-base as repo
RUN git clone https://github.com/bl4ckj4c/polito-se2-21-P01-SPG
COPY my-app/firebase-client polito-se2-21-P01-SPG/my-app/firebase-client
COPY server/firebase-server polito-se2-21-P01-SPG/server/firebase-server
COPY server/telegram/ polito-se2-21-P01-SPG/server/telegram
WORKDIR /polito-se2-21-P01-SPG
RUN git checkout tags/release-2

FROM node:alpine as build
COPY --from=repo polito-se2-21-P01-SPG/my-app /app/my-app
COPY --from=repo polito-se2-21-P01-SPG/server /app/server
WORKDIR /app/my-app
RUN npm install
WORKDIR /app/server
RUN npm install

FROM node:16.13.0-alpine as production
COPY --from=build /app /app
WORKDIR /app/my-app
EXPOSE 3000
CMD npm start & (cd ../server && node server.js)
